spring:
    application:
        name: Journal App

    data:
        mongodb:
            uri: mongodb://localhost:27017/journalApp
            # database: journaldb
            auto-index-creation: true
            # host: localhost
            # port: 27017
            # username:
            # password:

server:
    port: 8082
    servlet:
        context-path: /journal